import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/provider/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body className='scroll-smooth'>
				<Provider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange >
					{children}
				</Provider>
			</body>
		</html>
	)
}

export default RootLayout
